namespace LanRemote.Protocol;

public enum MessageType : byte
{
    ClientHello = 1,
    ServerHello = 2,
    SessionDecision = 3,
    SessionReady = 4,
    VideoFrame = 5,
    InputEvent = 6,
    Ping = 7,
    Pong = 8,
    Disconnect = 9,
    Error = 10,
    Metrics = 11,
    QualityProfileRequest = 12,
    QualityProfileApplied = 13,
    SecureAttentionRequest = 14,
    SecureAttentionResult = 15,
    DirectoryBrowseRequest = 16,
    DirectoryBrowseResponse = 17,
    DropTargetRequest = 18,
    DropTargetResponse = 19,
    ClipboardFilesRequest = 20,
    ClipboardFilesResponse = 21,
    FileUploadOffer = 22,
    FileUploadDecision = 23,
    FileUploadChunk = 24,
    FileUploadComplete = 25,
    FileUploadResult = 26,
    FileDownloadRequest = 27,
    FileDownloadOffer = 28,
    FileDownloadDecision = 29,
    FileDownloadChunk = 30,
    FileDownloadComplete = 31,
    FileDownloadResult = 32,
    FileTransferCancel = 33,
    ClipboardModeChanged = 34,
    ClipboardTextOffer = 35,
    ClipboardTextChunk = 36,
    ClipboardTextComplete = 37,
}
